version: '2'
services:
    angular-app:
        image: angular
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATA_MONGODB_URI=mongodb://angular-mongodb:27017
            - SPRING_DATA_MONGODB_DATABASE=angular
            - APP_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    angular-mongodb:
        extends:
            file: mongodb.yml
            service: angular-mongodb
